version: "3.8"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    container_name: web
    build: .
    ports:
      - "5432:8080"
    environment:
      - NODE_ENV=production

    depends_on:
      - redis
